import type { Prisma } from "@prisma/client";

import { AdminAuthError, requireMuHubAdmin } from "@/lib/admin-auth";
import { generateAndSaveProjectAiInsight } from "@/lib/project-ai-insight-service";
import {
  buildPublishProjectUpdateData,
  evaluateProjectPublishReadiness,
  PARTIAL_AI_PUBLISH_NOTICE,
  type BulkPublishItemResult,
  type ProjectPublishReadiness,
} from "@/lib/project-publishing";
import { prisma } from "@/lib/prisma";
import { writeProjectActionLog } from "@/lib/project-action-log";
import { refreshProjectGithubFacts } from "@/lib/github-sync";
import { resolveProjectGithubUrl } from "@/lib/project-evidence-context";

export const dynamic = "force-dynamic";

type BulkIntent = "publish" | "hide" | "archive";

const bulkProjectSelect = {
  id: true,
  name: true,
  slug: true,
  status: true,
  visibilityStatus: true,
  publishedAt: true,
  aiInsight: true,
  aiInsightStatus: true,
  aiContentStatus: true,
  aiKnowledgeJson: true,
  aiSourceSnapshot: true,
  aiStatus: true,
  tagline: true,
  description: true,
  primaryCategory: true,
  aiCardSummary: true,
  websiteUrl: true,
  githubUrl: true,
  sourceType: true,
  officialInfo: {
    select: {
      summary: true,
      fullDescription: true,
      useCases: true,
      whoFor: true,
      website: true,
    },
  },
  sources: {
    select: {
      kind: true,
      url: true,
      label: true,
      title: true,
      summary: true,
      isPrimary: true,
      visibility: true,
    },
  },
} satisfies Prisma.ProjectSelect;

type BulkProjectRow = Prisma.ProjectGetPayload<{ select: typeof bulkProjectSelect }>;

function readinessForRow(row: BulkProjectRow): ProjectPublishReadiness {
  return evaluateProjectPublishReadiness({
    id: row.id,
    name: row.name,
    slug: row.slug,
    status: row.status,
    visibilityStatus: row.visibilityStatus,
    publishedAt: row.publishedAt,
    aiInsight: row.aiInsight,
    aiInsightStatus: row.aiInsightStatus,
    aiContentStatus: row.aiContentStatus,
    aiKnowledgeJson: row.aiKnowledgeJson,
    aiSourceSnapshot: row.aiSourceSnapshot,
    aiStatus: row.aiStatus,
    tagline: row.tagline,
    description: row.description,
    primaryCategory: row.primaryCategory,
    aiCardSummary: row.aiCardSummary,
    websiteUrl: row.websiteUrl,
    githubUrl: row.githubUrl,
    sources: row.sources,
    officialInfo: row.officialInfo,
  });
}

function isOnlyMissingAiInsightBlocked(readiness: ProjectPublishReadiness): boolean {
  return (
    readiness.outcome === "blocked" &&
    readiness.issues.length === 1 &&
    readiness.knowledgeDiagnostics?.hasUsableKnowledge === false &&
    readiness.issues[0]?.startsWith("缺少 AI 结构化分析 / 认知卡内容")
  );
}

async function fetchBulkProjectRow(projectId: string): Promise<BulkProjectRow | null> {
  return prisma.project.findFirst({
    where: { id: projectId, deletedAt: null },
    select: bulkProjectSelect,
  });
}

async function publishReadyProject(row: BulkProjectRow, readiness: ProjectPublishReadiness): Promise<void> {
  await prisma.$transaction(async (tx) => {
    await tx.project.update({
      where: { id: row.id },
      data: buildPublishProjectUpdateData({
        publishedAt: row.publishedAt,
        primaryCategory: readiness.primaryCategory,
        readiness,
      }),
    });
    await writeProjectActionLog(
      {
        projectId: row.id,
        action: "publish",
        detail:
          readiness.publishQuality === "partial_ai"
            ? `项目列表批量发布（partial_ai）：${PARTIAL_AI_PUBLISH_NOTICE}`
            : "项目列表批量发布",
      },
      tx,
    );
  });
}

export async function POST(req: Request) {
  try {
    await requireMuHubAdmin();
  } catch (error) {
    if (error instanceof AdminAuthError) {
      return Response.json(
        { ok: false, error: error.message },
        { status: error.code === "UNAUTHORIZED" ? 401 : 403 },
      );
    }
    throw error;
  }

  const body = (await req.json().catch(() => ({}))) as {
    ids?: string[];
    intent?: BulkIntent;
  };
  const ids = Array.isArray(body.ids)
    ? [...new Set(body.ids.map((item) => String(item).trim()).filter(Boolean))]
    : [];
  const intent = body.intent;

  if (!ids.length) {
    return Response.json({
      ok: false,
      error: "未选择项目",
      processed: 0,
      publishedCount: 0,
      blockedCount: 0,
      skippedCount: 0,
      warningCount: 0,
      autoGeneratedAiInsightCount: 0,
      aiInsightGenerationFailedCount: 0,
      counts: {
        processed: 0,
        published: 0,
        blocked: 0,
        skipped: 0,
        warnings: 0,
        autoGeneratedAiInsight: 0,
        aiInsightGenerationFailed: 0,
      },
    }, { status: 400 });
  }

  if (intent !== "publish" && intent !== "hide" && intent !== "archive") {
    return Response.json({ ok: false, error: "不支持的批量操作。" }, { status: 400 });
  }

  const rows = await prisma.project.findMany({
    where: { id: { in: ids }, deletedAt: null },
    select: bulkProjectSelect,
  });

  if (intent === "publish") {
    const published: BulkPublishItemResult[] = [];
    const skipped: BulkPublishItemResult[] = [];
    const blocked: BulkPublishItemResult[] = [];
    const partial_ai: BulkPublishItemResult[] = [];
    const warnings: BulkPublishItemResult[] = [];
    const autoGeneratedAiInsight: BulkPublishItemResult[] = [];
    const aiInsightGenerationFailed: BulkPublishItemResult[] = [];

    for (const initialRow of rows) {
      let row = initialRow;
      const itemBase = { id: row.id, name: row.name, slug: row.slug };

      if (row.status !== "DRAFT") {
        skipped.push({
          ...itemBase,
          reason: row.status === "PUBLISHED"
            ? "项目已发布，不参与批量发布"
            : `项目状态为 ${row.status}，仅 DRAFT 可批量发布`,
        });
        continue;
      }

      let readiness = readinessForRow(row);
      if (isOnlyMissingAiInsightBlocked(readiness)) {
        try {
          await generateAndSaveProjectAiInsight(row.id, {
            reason: "bulk_publish_preflight",
          });
          autoGeneratedAiInsight.push({
            ...itemBase,
            notice: "批量发布前已自动生成 AI 认知卡",
          });
          const refreshed = await fetchBulkProjectRow(row.id);
          if (!refreshed) {
            skipped.push({
              ...itemBase,
              reason: "项目不存在或已删除",
            });
            continue;
          }
          row = refreshed;
          readiness = readinessForRow(row);
        } catch (error) {
          const reason = error instanceof Error ? error.message : "AI 认知卡生成失败";
          aiInsightGenerationFailed.push({
            ...itemBase,
            reason,
          });
          blocked.push({
            ...itemBase,
            issues: [`AI 认知卡自动生成失败：${reason}`],
            diagnostics: readiness.knowledgeDiagnostics,
            reason: `AI 认知卡自动生成失败：${reason}`,
          });
          continue;
        }
      }

      if (readiness.warnings.length > 0) {
        warnings.push({
          ...itemBase,
          warnings: readiness.warnings,
          reason: readiness.warnings.join("；"),
        });
      }

      if (readiness.outcome === "skipped") {
        skipped.push({
          ...itemBase,
          reason: readiness.issues[0] ?? "已跳过",
        });
        continue;
      }

      if (readiness.outcome === "blocked") {
        blocked.push({
          ...itemBase,
          issues: readiness.issues,
          diagnostics: readiness.knowledgeDiagnostics,
          reason: readiness.issues.join("；"),
        });
        continue;
      }

      try {
        const repoUrl = resolveProjectGithubUrl({
          githubUrl: row.githubUrl,
          sources: row.sources,
        });
        if (repoUrl) {
          const githubRefresh = await refreshProjectGithubFacts(row.id);
          if (!githubRefresh.ok) {
            warnings.push({
              ...itemBase,
              warnings: ["GitHub facts 刷新失败，已跳过增强刷新"],
              reason: githubRefresh.lastFetchError ?? "GitHub facts 刷新失败",
            });
            console.warn("[bulk-action] github facts refresh failed before publish", {
              projectId: row.id,
              slug: row.slug,
              lastFetchError: githubRefresh.lastFetchError,
            });
          }
        }

        await publishReadyProject(row, readiness);

        if (readiness.publishQuality === "partial_ai") {
          partial_ai.push({
            ...itemBase,
            notice: readiness.notice ?? PARTIAL_AI_PUBLISH_NOTICE,
          });
        } else {
          published.push(itemBase);
        }
      } catch (error) {
        blocked.push({
          ...itemBase,
          reason: error instanceof Error ? error.message : "发布失败",
        });
      }
    }

    const missingIds = ids.filter((id) => !rows.some((row) => row.id === id));
    for (const id of missingIds) {
      skipped.push({
        id,
        name: id,
        slug: id,
        reason: "项目不存在或已删除",
      });
    }

    const publishedCount = published.length + partial_ai.length;
    const blockedCount = blocked.length;
    const skippedCount = skipped.length;
    const warningCount = warnings.length;
    const autoGeneratedAiInsightCount = autoGeneratedAiInsight.length;
    const aiInsightGenerationFailedCount = aiInsightGenerationFailed.length;
    const processed = publishedCount + blockedCount + skippedCount;

    return Response.json({
      ok: true,
      intent,
      count: processed,
      processed,
      publishedCount,
      blockedCount,
      skippedCount,
      warningCount,
      autoGeneratedAiInsightCount,
      aiInsightGenerationFailedCount,
      counts: {
        processed,
        published: publishedCount,
        blocked: blockedCount,
        skipped: skippedCount,
        warnings: warningCount,
        autoGeneratedAiInsight: autoGeneratedAiInsightCount,
        aiInsightGenerationFailed: aiInsightGenerationFailedCount,
      },
      published,
      skipped,
      blocked,
      warnings,
      partial_ai,
      autoGeneratedAiInsight,
      aiInsightGenerationFailed,
      message:
        partial_ai.length > 0
          ? `${PARTIAL_AI_PUBLISH_NOTICE}；${partial_ai.length} 个项目为 partial_ai`
          : undefined,
    });
  }

  await prisma.$transaction(async (tx) => {
    for (const row of rows) {
      if (intent === "hide") {
        await tx.project.update({
          where: { id: row.id },
          data: {
            status: row.status === "PUBLISHED" ? "READY" : row.status,
            visibilityStatus: "HIDDEN",
            isPublic: false,
          },
        });
        await writeProjectActionLog(
          {
            projectId: row.id,
            action: "hide",
            detail: "项目列表批量隐藏",
          },
          tx,
        );
      } else {
        await tx.project.update({
          where: { id: row.id },
          data: {
            status: "ARCHIVED",
            visibilityStatus: "HIDDEN",
            isPublic: false,
          },
        });
        await writeProjectActionLog(
          {
            projectId: row.id,
            action: "archive",
            detail: "项目列表批量归档",
          },
          tx,
        );
      }
    }
  });

  return Response.json({ ok: true, count: rows.length, intent });
}
